experiment:
  name: vae_mnist

paths:
  dataset_dir: datasets
  runs_dir: runs

dataset:
  name: mnist
  train: true
  train_split: 0.8
  shape: [1, 28, 28]

dataloader:
  batch_size: 128
  shuffle_train: true
  shuffle_validation: false
  num_workers: 0

training:
  epochs: 200
  learning_rate: 0.001
  start_weights: random

loss:
  name: vae_loss
  log_prob_function: continuous_bernoulli

model:
  name: vae

  encoder:
    latent_dim: 32
    out_channels: [32, 64, 128, 128]
    kernels: [3, 3, 3, 3]
    strides: [2, 2, 2, 1]
    paddings: [1, 1, 1, 1]

optimizer:
  name: adam

lr_scheduler:
  name: reduce_lr_on_plateau
  treshold: 0.5
  treshold_mode: abs


scoring:
  pretrained_model: Null
  out_distribution_datasets: [fashion_mnist, organamnist, kmnist]

  dataloader:
    batch_size: 128
    num_workers: 0

  signals:
    likelihood:
      enabled: true
    typicality:
      enabled: true
    gradnorm:
      enabled: true
    latent_encoding:
      enabled: true
    hole_mass:
      enabled: true


seed: 42